[build]
  publish = "."
  command = "echo 'No build process needed for static site'"

# Redirect rules for clean URLs and SPA behavior
[[redirects]]
  from = "/admin"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/portal"
  to = "/student-portal.html"
  status = 200

[[redirects]]
  from = "/booking"
  to = "/booking.html"
  status = 200

[[redirects]]
  from = "/policies"
  to = "/policies.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# HTML files - short cache for updates
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Environment variables (these will be set in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18" 